CONSUMER_API_KEY = '3iuAbxrkuqCKAYWFgZPkfxNoW'                            
CONSUMER_API_SELECT_KEY = 'IzGxscffStnKzMGfDd4QepOEsQWyJVUYrLAKr8oQzY8btO8jUL'    
ACCESS_TOKEN = '3244069022-55rfyYymFuBuvCMM8CwZ4CYAxTOjXPteloxisZT'    
ACCESS_TOKEN_SECRET = 'cI96c7sgsTP4yCENRoDzrIsUe4tSMTIDJ7vYRWAaOCSQK'
